name: First action by Jesus

on: workflow_dispatch

jobs:
  jesus_help:
    name: Jesus help
    runs-on: ubuntu-latest
    steps:
      - name: Running first script
        run: echo "Hello World, this is my first action by Jesus"